baseURL = "https://msmbrc.github.io/"
languageCode = "it-IT"
title = "MSMBRC"

# Paginazione: 7 post per pagina

[params]
  author      = "MSMBRC"
  handle      = ""
  bio         = "Tecnologia, arte, videogame, film libri e cose a caso."
  location    = ""
  twitter     = ""
  email       = ""
  copyright   = "© 2026 MSMBRC"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Permette HTML raw nei file .md (necessario per i shortcode inline)
      unsafe = true
[pagination]
  pagerSize = 7
