baseURL = "https://msmbrc.github.io/"
languageCode = "it-IT"
title = "MSMBRC"

# Paginazione: 7 post per pagina

[params]
  author      = "MSMBRC"
  handle      = ""
  bio         = "Vivo a Milano. Gioco ai videogame, talvolta leggo e corro ma soprattutto prendo appunti. Dalle nove alle diciotto sono UX e UI Designer."
  location    = "Milano"
  twitter     = "asd"
  email       = "massimiliano.barci@proton.me"
  copyright   = "© 2026 MSMBRC"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Permette HTML raw nei file .md (necessario per i shortcode inline)
      unsafe = true
[pagination]
  pagerSize = 7
